name: Undo last JSON modification

on:
  workflow_dispatch:

jobs:
  undo-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Revert last commit on JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git log --pretty=oneline -n 5
          git checkout HEAD~1 data/Word_to_Json_BiblioTeacher.json
          git add data/Word_to_Json_BiblioTeacher.json
          git commit -m "Undo last JSON modification"
          git push
